[package]
name = "chat-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
futures = "0.3"
ratatui = "0.20.1"
crossterm = "0.27"
log = "0.4"
env_logger = "0.9"
